#!/bin/bash

while true
do
	echo '1) Nano'
	echo '2) Vim'
	echo '3) Links'
	echo '4) exit'

	read num
	if [[ $num -eq 1 ]]
		then nano
		exit 
	fi

	if [[ $num -eq 2 ]]
		then vi
		exit 
	fi

	if [[ $num -eq 3 ]]
		then Links
		exit 
	fi


	if [[ $num -eq 4 ]]
		then exit 
	fi

	echo 'Incorrect number!'
done

