#!/bin/bash

temp_file=temp/errors.log

grep -r -h "^ACPI*" /var/log/ > $temp_file
grep -h -E "/[A-Za-z0-9][A-Za-z0-9./]*\.[A-Za-z0-9]+\s" $temp_file



# while read -r line; do
# 	for word in $line
# 	do
#     	if [ -f $word ]; then
# 		    echo $line
# 		    break
# 		fi
# 	done
# done < $temp_file